  const activityStorage= [
    { activity:"Sailing",
       maxTemperatureLow:0,
        probabilityOfPrecipitation:5,
         windSpeed:15,
          image:["img/sailing.jpg","Two sailboats in the water."],
            imageico:["img/sailingico.jpg","Sailing Icon"],
             activityTense: 'sail'
    },
    { activity:"Hiking",
       maxTemperatureLow:0,
        probabilityOfPrecipitation:5,
         windSpeed:100,
           image:["img/hiking.jpg","A person on a mountain peak."],
            imageico: ["img/hikingico.jpg","Hiking Icon"],
             activityTense: 'hike'
    },
    { activity:"Fishing",
       maxTemperatureLow:0,
        probabilityOfPrecipitation:5,
         windSpeed:10,
           image:["img/fishing.jpg","Fishing rod cast into the water."],
            imageico: ["img/fishingico.jpg","Fishing Icon"],
             activityTense: 'fish'
    },
    { activity:"Drone_Flying",
       maxTemperatureLow:100,
        probabilityOfPrecipitation:2,
         windSpeed:10,
           image:["img/drone.jpg","Drone flying near sunset."],
            imageico:["img/droneico.jpg","Drone Flying Icon"],
             activityTense: 'fly a drone'
    },
    { activity:"Kite_Flying",
       maxTemperatureLow:32,
        probabilityOfPrecipitation:1,
         windSpeed:100,
           image:["img/kite.jpg","Group of kites in the sky."],
            imageico:["img/kiteico.jpg","Kite Flying Icon"],
             activityTense: 'fly a kite'
    },
    { activity:"Star_Gazing",
       maxTemperatureLow:32,
        probabilityOfPrecipitation:2,
         windSpeed:100,
           image:["img/stars.jpg","A person looking at the stars on the side of a mountain."],
            imageico: ["img/starsico.jpg","Star Gazing Icon"],
             activityTense: 'gaze at the stars'
    },
    { activity:"Baseball",
       maxTemperatureLow:45,
        probabilityOfPrecipitation:1,
         windSpeed:100,
           image:["img/baseball.jpg","Baseball, baseball mitten and bat."],
            imageico:["img/baseballico.jpg","Baseball Icon"],
             activityTense: 'play baseball'
  },
    { activity:"Rock_Climbing",
       maxTemperatureLow:40,
        probabilityOfPrecipitation:1,
         windSpeed:100,
           image:["img/rock.jpg","Woman climbing a mountain-side"],
            imageico:["img/rockico.jpg","Rock Climbing Icon"],
             activityTense: 'rock climb'
    },
    { activity:"Cycling",
       maxTemperatureLow:50,
        probabilityOfPrecipitation:3,
         windSpeed:5,
           image:["img/cycling.jpg","Cyclist on an road."],
            imageico:["img/cyclingico.jpg","Cycling Icon"],
             activityTense: 'bike'
    },
    { activity:"Motorcycling",
       maxTemperatureLow:60,
        probabilityOfPrecipitation:2,
         windSpeed:10,
           image:["img/moto.png","A dirt bike."],
            imageico:["img/motoico.jpg","Motorcycling Icon"],
             activityTense: 'go for a ride'
    },
    { activity:"Skateboarding",
       maxTemperatureLow:40,
        probabilityOfPrecipitation:1,
         windSpeed:5,
           image:["img/skatepage.jpg","A skateboard resting on its side."],
            imageico:["img/skateico.png","Skateboarding Icon"],
             activityTense: 'go skate'
    },
    { activity:"Running",
       maxTemperatureLow:20,
        probabilityOfPrecipitation:3,
         windSpeed:10,
           image:["img/runpage.jpg","Numbers on a running track."],
            imageico:["img/runico.png","Running Icon"],
             activityTense: 'go for a run'
    },
    { activity:"Basketball",
       maxTemperatureLow:40,
        probabilityOfPrecipitation:1,
         windSpeed:30,
           image:["img/larryjohnson.jpeg","Legendary basketball player larry Johnson in a Charlotte Hornets warm up suit."],
            imageico:["img/hoopico.png","Basketball Icon"],
             activityTense: 'go play basketball'
    },
    { activity:"Golf",
       maxTemperatureLow:50,
        probabilityOfPrecipitation:1,
         windSpeed:30,
           image:["img/golfpage.png","Close shot of a golfball on the green."],
            imageico:["img/golfico.png","Golf Icon"],
             activityTense: 'go golfing'
    },
    { activity:"Football",
       maxTemperatureLow:10,
        probabilityOfPrecipitation:3,
         windSpeed:40,
           image:["img/footpage.png","Close shot of an Atlanta Falcons football."],
            imageico:["img/footico.png","Football Icon"],
             activityTense: 'go play football'
    },
    { activity:"Tennis",
       maxTemperatureLow:55,
        probabilityOfPrecipitation:1,
         windSpeed:15,
           image:["img/tennpage.jpg","Group of tennis balls on a tennis court."],
            imageico:["img/tennico.png","Tennis Icon"],
             activityTense: 'go play tennis'
    },
    { activity:"Soccer",
       maxTemperatureLow:55,
        probabilityOfPrecipitation:3,
         windSpeed:15,
           image:["img/soccpage.png","Close shot of a soccer ball in grass."],
            imageico:["img/soccico.png","Soccer Icon"],
             activityTense: 'go play soccer'
    },
    { activity:"Surfing",
       maxTemperatureLow:40,
        probabilityOfPrecipitation:4,
         windSpeed:20,
           image:["img/surfpage.png","Very large barrel shaped wave."],
            imageico:["img/surfico.png","Surfing Icon"],
             activityTense: 'go surfing'
      }
    ];
    
