  let activityStorage= [
    { activity:"Sailing",
       maxTemperatureLow:0,
        probabilityOfPrecipitation:5,
         windSpeed:15,
          describe:"Sailing is ...",
           image:"img/sailing.jpg",
            imageico:"img/sailingico.jpg",
             activityTense: 'sail.'
    },
    { activity:"Hiking",
       maxTemperatureLow:0,
        probabilityOfPrecipitation:5,
         windSpeed:100,
          describe:"Hiking is ...",
           image:"img/hiking.jpg",
            imageico: "img/hikingico.jpg",
             activityTense: 'hike.'
    },
    { activity:"Fishing",
       maxTemperatureLow:0,
        probabilityOfPrecipitation:5,
         windSpeed:10,
          describe:"Fishing is ...",
           image:"img/fishing.jpg",
            imageico: "img/fishingico.jpg",
             activityTense: 'fish.'
    },
    { activity:"Drone_Flying",
       maxTemperatureLow:100,
        probabilityOfPrecipitation:2,
         windSpeed:10,
          describe:"Drone flying is ...",
           image:"img/drone.jpg",
            imageico:"img/droneico.jpg",
             activityTense: 'fly a drone.'
    },
    { activity:"Kite_Flying",
       maxTemperatureLow:32,
        probabilityOfPrecipitation:1,
         windSpeed:100,
          describe:"Kite flying is ...",
           image:"img/kite.jpg",
            imageico:"img/kiteico.jpg",
             activityTense: 'fly a kite.'
    },
    { activity:"Star_Gazing",
       maxTemperatureLow:32,
        probabilityOfPrecipitation:2,
         windSpeed:100,
          describe:"Star gazing is ...",
           image:"img/stars.jpg",
            imageico: "img/starsico.jpg",
             activityTense: 'gaze at the stars.'
    },
    { activity:"Baseball",
       maxTemperatureLow:45,
        probabilityOfPrecipitation:1,
         windSpeed:100,
          describe:"baseball is ...",
           image:"img/baseball.jpg",
            imageico:"img/baseballico.jpg",
             activityTense: 'play baseball.'
  },
    { activity:"Rock_Climbing",
       maxTemperatureLow:40,
        probabilityOfPrecipitation:1,
         windSpeed:100,
          describe:"Rock Climbing is ...",
           image:"img/rock.jpg",
            imageico:"img/rockico.jpg",
             activityTense: 'rock climb.'
    },
    { activity:"Cycling",
       maxTemperatureLow:50,
        probabilityOfPrecipitation:3,
         windSpeed:5,
          describe:"Cycling is ...",
           image:"img/cycling.jpg",
            imageico:"img/cyclingico.jpg",
             activityTense: 'bike.'
    },
    { activity:"Motorcycling",
       maxTemperatureLow:60,
        probabilityOfPrecipitation:2,
         windSpeed:10,
          describe:"Motorcyling is ...",
           image:"img/moto.jpg",
            imageico:"img/motoico.jpg",
             activityTense: 'go for a ride.'
    },
    { activity:"Skateboarding",
       maxTemperatureLow:40,
        probabilityOfPrecipitation:1,
         windSpeed:5,
          describe:"Skateboarding is ...",
           image:"img/skatepage.jpg",
            imageico:"img/skateico.png",
             activityTense: 'go skate.'
    },
    { activity:"Running",
       maxTemperatureLow:20,
        probabilityOfPrecipitation:3,
         windSpeed:10,
          describe:"Running is ...",
           image:"img/runpage.jpg",
            imageico:"img/runico.png",
             activityTense: 'go for a run.'
    },
    { activity:"Basketball",
       maxTemperatureLow:40,
        probabilityOfPrecipitation:1,
         windSpeed:30,
          describe:"Basketball is ...",
           image:"img/hooppage.jpg",
            imageico:"img/hoopico.png",
             activityTense: 'go play basketball.'
    },
    { activity:"Golf",
       maxTemperatureLow:50,
        probabilityOfPrecipitation:1,
         windSpeed:30,
          describe:"Golf is ...",
           image:"img/golfpage.png",
            imageico:"img/golfico.png",
             activityTense: 'go golfing.'
    },
    { activity:"Football",
       maxTemperatureLow:10,
        probabilityOfPrecipitation:3,
         windSpeed:40,
          describe:"Football is ...",
           image:"img/footpage.png",
            imageico:"img/footico.png",
             activityTense: 'go play football.'
    },
    { activity:"Tennis",
       maxTemperatureLow:55,
        probabilityOfPrecipitation:1,
         windSpeed:15,
          describe:"Tennis is ...",
           image:"img/tennpage.jpg",
            imageico:"img/tennico.png",
             activityTense: 'go play tennis.'
    },
    { activity:"Soccer",
       maxTemperatureLow:55,
        probabilityOfPrecipitation:3,
         windSpeed:15,
          describe:"Soccer is ...",
           image:"img/soccpage.png",
            imageico:"img/soccico.png",
             activityTense: 'go play soccer.'
    },
    { activity:"Surfing",
       maxTemperatureLow:40,
        probabilityOfPrecipitation:4,
         windSpeed:20,
          describe:"Surfing is ...",
           image:"img/surfpage.png",
            imageico:"img/surfico.png",
             activityTense: 'go surfing.'
      }
    ];
    
